/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
   
    // Apply the settings fix for the goomp plugin https://github.com/diffplug/goomph/issues/203
    id("com.diffplug.configuration-cache-for-platform-specific-build") version "3.44.0"
}

rootProject.name = "dynamo-hia"
include("acdm", "utilities", "application")
