#!/bin/bash
rm -rf ./nl/rivm/emi/CVS
rm -rf ./nl/rivm/emi/cdm/CVS
rm -rf ./nl/rivm/emi/cdm/exceptions/CVS
rm -rf ./nl/rivm/emi/dynamo/CVS
rm -rf ./nl/rivm/emi/dynamo/application/CVS
rm -rf ./nl/rivm/emi/dynamo/data/CVS
rm -rf ./nl/rivm/emi/dynamo/data/containers/CVS
rm -rf ./nl/rivm/emi/dynamo/data/factories/CVS
rm -rf ./nl/rivm/emi/dynamo/data/factories/test/CVS
rm -rf ./nl/rivm/emi/dynamo/data/riskfactor/CVS
rm -rf ./nl/rivm/emi/dynamo/data/test/CVS
rm -rf ./nl/rivm/emi/dynamo/data/transition/CVS
rm -rf ./nl/rivm/emi/dynamo/data/types/CVS
rm -rf ./nl/rivm/emi/dynamo/data/types/test/CVS
rm -rf ./nl/rivm/emi/dynamo/data/values/CVS
rm -rf ./nl/rivm/emi/dynamo/data/writers/CVS
rm -rf ./nl/rivm/emi/dynamo/data/writers/test/CVS
rm -rf ./nl/rivm/emi/dynamo/databinding/CVS
rm -rf ./nl/rivm/emi/dynamo/databinding/converters/CVS
rm -rf ./nl/rivm/emi/dynamo/databinding/updatevaluestrategy/CVS
rm -rf ./nl/rivm/emi/dynamo/estimation/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/actions/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/main/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/main/test/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/panels/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/panels/button/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/panels/help/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/parametercontrols/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/parametercontrols/prototype/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/parametercontrols/prototype/test/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/parametercontrols/test/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/poc/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/treecontrol/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/treecontrol/examples/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/treecontrol/test/CVS
rm -rf ./nl/rivm/emi/dynamo/ui/windows/CVS
