/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dynamo.hia.java-library-conventions")
    id("eclipse")
}


dependencies {
    implementation("commons-configuration:commons-configuration:1.5")
}
