/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dynamo.hia.java-library-conventions")
    id("eclipse")
}

repositories {
    mavenCentral()
}


dependencies {

    implementation("junit:junit:4.13.2")

    implementation("commons-logging:commons-logging:1.2")
    implementation("commons-configuration:commons-configuration:1.5")
    implementation("commons-collections:commons-collections:3.2.2")
    implementation("commons-lang:commons-lang:2.6")
    implementation("log4j:log4j:1.2.17")
    implementation("gov.nist.math.jama:gov.nist.math.jama:1.1.1")
}



tasks.test {
    //use Junit for tests
    useJUnitPlatform()
}
