/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dynamo.hia.java-application-conventions")
    id("eclipse")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("dynamo.hia.app.App")
}
