/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dynamo.hia.app;
class MessageUtilsTest {
//    @Test void testGetMessage() {
//        assertEquals("Hello      World!", MessageUtils.getMessage());
//    }
}
